<?php 

$input = $_GET['ingredientNameValue'];


$wordPrompts = array(
    "salt",
    "pepper",
    "olive oil",
    "garlic",
    "onion",
    "tomato",
    "flour",
    "sugar",
    "butter",
    "eggs",
    "milk",
    "cheese",
    "chicken",
    "beef",
    "rice",
    "pasta",
    "bread",
    "lemon",
    "honey",
    "soy sauce",
    "ginger",
    "cinnamon",
    "vanilla",
    "cream",
    "thyme",
    "rosemary",
    "oregano",
    "basil",
    "parsley",
    "cilantro",
    "cumin",
    "paprika",
    "cayenne pepper",
    "mustard",
    "ketchup",
    "mayonnaise",
    "vinegar",
    "bell pepper",
    "carrot",
    "potato",
    "avocado",
    "lettuce",
    "cucumber",
    "zucchini",
    "spinach",
    "kale",
    "broccoli",
    "asparagus",
    "mushroom",
    "sweet potato",
    "corn",
    "peas",
    "beans",
    "chickpeas",
    "lentils",
    "quinoa",
    "nuts",
    "almonds",
    "walnuts",
    "pecans",
    "cashews",
    "peanuts",
    "chocolate",
    "vanilla extract",
    "maple syrup",
    "coconut milk",
    "sour cream",
    "yogurt",
    "mayonnaise",
    "mustard",
    "hot sauce",
    "salsa",
    "sriracha",
    "sesame oil",
    "fish sauce",
    "shrimp",
    "salmon",
    "tuna",
    "lobster",
    "shrimp",
    "crab",
    "scallop",
    "clam",
    "mussels",
    "squid",
    "octopus",
    "tofu",
    "tempeh",
    "seitan",
    "miso",
    "soy milk"
);




$filteredPrompts = array_filter($wordPrompts, function ($word) use ($input) {
    return stripos($word, $input) !== false;
});


echo json_encode(array_values($filteredPrompts));
